name: Notify Docs Repo on Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch to pyssp.github.io
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PYSSP_DOCS_DISPATCH_TOKEN }}
          repository: sikaxn/pyssp.github.io
          event-type: pyssp_release_published
